name: Workflow Demo

on: 
  push

env:
  ACCESS_ID: ${{ secrets.ACCESS_ID }}
  ACCESS_ID: kode-kloud-123456
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID